routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function() {

    /************************* USER *****************************/
    Route::resource('users', \App\Http\Controllers\UserController::class);

    /************************* USER *****************************/
    Route::resource('projects', \App\Http\Controllers\ProjectController::class);

    /************************* PROJECT *****************************/
    Route::resource('users', \App\Http\Controllers\UserController::class);

    Route::prefix('task')->group(function () {
        Route::get('/done/{id}', [App\Http\Controllers\ProjectController::class, 'task_done'])->name('task.done');
    });


    Route::get('/home', function() {
        return view('home');
    })->name('home');

});

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    use HasFactory;

  protected $fillable = [
        'user_id',
        'project_name',
        'brief_description',
        'date_line',
        'status',
        'completion_time'
    ];

        public function user()
    {
        return $this->hasOne(User::class,'id','user_id');
    }

}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Project;
use App\Models\User;


class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $projects = Project::with('user')->get();
       return view('projects.index', [
        'projects' => $projects
    ]);
   }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::all();

        return view('projects.create',compact('users'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'user_id' => 'required',
            'project_name' => 'required',
            'brief_description' => 'required',
            'date_line' => 'required'
        ]);


        $project = Project::create([
           'user_id'          => $request->user_id,
           'project_name'    => $request->project_name,
           'brief_description'    => $request->brief_description,
           'date_line'    => $request->date_line,

       ]);     

        return redirect()->route('projects.index')
        ->with('success_message', 'Berhasil menambah Project baru');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

       $project = Project::find($id);
       $users = User::all();
       if (!$project) return redirect()->route('projects.index')
        ->with('error_message', 'project dengan id '.$id.' tidak ditemukan');
    return view('projects.edit',compact('project','users'));
}

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $project = Project::find($id);
        $project->user_id = $request->user_id;
        $project->project_name = $request->project_name;
        $project->brief_description = $request->brief_description;
        $project->date_line = $request->date_line;
        $project->save();
        return redirect()->route('projects.index')
        ->with('success_message', 'Berhasil mengubah project');
    }


    public function task_done($id)
    {
       $project = Project::find($id);
       $project->status = "done";
        $project->completion_time = date('Y-m-d G:i:s');

       $project->save();
       return redirect()->route('projects.index')
       ->with('success_message', 'berhasil');

   }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $class = Project::findOrFail($id);
        $class->delete();

        if($class){
           return redirect()->route('projects.index')
           ->with('success_message', 'Berhasil menghapus project');
       }else{
        return redirect()->route('projects.index')
        ->with('error_message', 'gagal menghapus project');
    }
}
}

resources/views/projects/create.blade.php
@extends('adminlte::page')

@section('title', 'Tambah Project')

@section('content_header')

<h1 class="m-0 text-dark">Tambah Project</h1>
@stop

@section('content')

<form action="{{route('projects.store')}}" method="post">
    @csrf
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">


                  <div class="form-group">
                    <label>Anggota </label>
                    <select name="user_id" class="form-control">
                        <option value="">-- PILIH ANGGOTA --</option>
                        @foreach ($users as $user)
                        <option value="{{ $user->id }}">{{ $user->name }}</option>
                        @endforeach
                    </select>
                    @error('category_id')
                    <div class="invalid-feedback" style="display: block">
                        {{ $message }}
                    </div>
                    @enderror
                </div>


                <div class="form-group">
                    <label for="exampleInputName">Nama Project</label>
                    <input type="text" class="form-control @error('project_name') is-invalid @enderror" id="exampleInputName" placeholder="Nama Project" name="project_name" value="{{old('project_name')}}">
                    @error('project_name') <span class="text-danger">{{$message}}</span> @enderror
                </div>

                <div class="form-group">
                    <label for="exampleInputEmail">Brief Description</label>
                    <textarea id="exampleInputEmail" class="form-control @error('brief_description') is-invalid @enderror" name="brief_description" value="{{old('brief_description')}}" rows="4" cols="50">

                    </textarea>

                    @error('brief_description') <span class="text-danger">{{$message}}</span> @enderror
                </div>

              
                <div class="form-group">
                    <label for="exampleInputName">Deadline Project</label>
             
                    <input type="text" class="datepicker-here form-control @error('date_line') is-invalid @enderror" data-language='en' data-position='top left' placeholder="Deadline Project" name="date_line" value="{{old('date_line')}}">
                    @error('date_line') <span class="text-danger">{{$message}}</span> @enderror
                </div>

            </div>

            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Simpan</button>
                <a href="{{route('users.index')}}" class="btn btn-default">
                    Batal
                </a>
            </div>
        </div>
    </div>
</div>
</form>
@stop

resources/views/projects/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit Project')

@section('content_header')
<h1 class="m-0 text-dark">Edit Project</h1>
@stop

@section('content')
<form action="{{route('projects.update', $project)}}" method="post">
    @method('PUT')
    @csrf
    <div class="row">
        <div class="col-12">
            <div class="card">

                <div class="card-body">
                    <div class="alert alert-secondary" role="alert">
                        {{ $project->status }}, adalah status saat ini
                  </div>
                  <div class="form-group">
                     <label>ANGGOTA</label>
                     <select name="user_id" class="form-control">
                        <option value="">-- PILIH ANGGOTA --</option>
                        @foreach ($users as $users)
                        @if($project->user_id == $users->id)
                        <option value="{{ $users->id  }}" selected>{{ $users->name }}
                        </option>
                        @else
                        <option value="{{ $users->id  }}">{{ $users->name }}</option>
                        @endif
                        @endforeach
                    </select>
                    @error('user_id')
                    <div class="invalid-feedback" style="display: block">
                        {{ $message }}
                    </div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="exampleInputName">Nama</label>
                    <input type="text" class="form-control @error('project_name') is-invalid @enderror" id="exampleInputName" placeholder="project name" name="project_name" value="{{$project->project_name ?? old('project_name')}}">
                    @error('project_name') <span class="text-danger">{{$message}}</span> @enderror
                </div>

                <div class="form-group">
                    <label for="exampleInputEmail">brief description</label>
                    <input type="brief_description" class="form-control @error('brief_description') is-invalid @enderror" id="exampleInputEmail" placeholder=" brief description" name="brief_description" value="{{$project->brief_description ?? old('brief_description')}}">
                    @error('brief_description') <span class="text-danger">{{$message}}</span> @enderror
                </div>

                <div class="form-group">
                    <label for="exampleInputEmail">dateline</label>
                    <input type="text" class="datepicker-here form-control @error('date_line') is-invalid @enderror" data-language='en' data-position='top left' placeholder="Deadline Project" name="date_line" value="{{$project->date_line ?? old('date_line')}}">

                    @error('date_line') <span class="text-danger">{{$message}}</span> @enderror

                </div>


            </div>

            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Simpan</button>
                <a href="{{route('projects.index')}}" class="btn btn-default">
                    Batal
                </a>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/projects/index.blade.php
@extends('adminlte::page')

@section('title', 'List Project')

@section('content_header')
<h1 class="m-0 text-dark">List Project</h1>
@stop

@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">

                <a href="{{route('projects.create')}}" class="btn btn-primary mb-2">
                    Tambah
                </a>

                <table class="table table-hover table-bordered table-stripped" id="example3">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Nama Anggota</th>
                            <th>Nama Project</th>
                            <th>Brief Description</th>
                            <th>Deadline Project</th>
                            <th>Completion time</th>
                            <th>Status</th>
                            <th>Action</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach($projects as $key => $project)
                        <tr>
                            <td>{{$key+1}}</td>
                            <td>{{$project->user->name }}</td>
                            <td>{{$project->project_name}}</td>
                            <td>{{$project->brief_description}}</td>
                            <td>{{$project->date_line }}</td>
                            <td>{{$project->completion_time }}</td>
                            <td>{{$project->status }}</td>

                            <td>
                                <a href="{{route('projects.edit', $project)}}" class="btn btn-secondary btn-xs">
                                    Edit
                                </a>
                                <a href="{{route('projects.destroy', $project)}}" onclick="notificationBeforeDelete(event, this)" class="btn btn-danger btn-xs">
                                    Delete
                                </a>

                                @if($project->status == "progress")

                                <a href="{{route('task.done', $project->id)}}" class="btn btn-primary btn-xs">
                                 Success Progress
                             </a>
                             @endif
                         </td>
                     </tr>
                     @endforeach
                 </tbody>
             </table>

         </div>
     </div>
 </div>
</div>
@stop

@push('js')
<form action="" id="delete-form" method="post">
    @method('delete')
    @csrf
</form>
<script>
    $('#example3').DataTable({
        "responsive": true,
    });

    function notificationBeforeDelete(event, el) {
        event.preventDefault();
        if (confirm('Apakah anda yakin akan menghapus data ? ')) {
            $("#delete-form").attr('action', $(el).attr('href'));
            $("#delete-form").submit();
        }
    }

</script>
@endpush